// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.1.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['poisson.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_00d4fefb25fc8ed8563136725dd7f20b01dabe87





ufc_finite_element element_00d4fefb25fc8ed8563136725dd7f20b01dabe87 =
{
  .signature = "FiniteElement('Lagrange', triangle, 1)",
  .cell_shape = triangle,
  .element_type = ufc_basix_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .block_size = 1,
  .family = "Lagrange",

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_00d4fefb25fc8ed8563136725dd7f20b01dabe87

// Code for element element_30501addce65c40f51d2333fb2adc3f5a9795426

int value_shape_element_30501addce65c40f51d2333fb2adc3f5a9795426[1] = { 2 };
int reference_value_shape_element_30501addce65c40f51d2333fb2adc3f5a9795426[1] = { 2 };
ufc_finite_element* sub_elements_element_30501addce65c40f51d2333fb2adc3f5a9795426[2] = { &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87, &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87 };

ufc_finite_element element_30501addce65c40f51d2333fb2adc3f5a9795426 =
{
  .signature = "VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)",
  .cell_shape = triangle,
  .element_type = ufc_blocked_element,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 1,
  .value_shape = value_shape_element_30501addce65c40f51d2333fb2adc3f5a9795426,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_30501addce65c40f51d2333fb2adc3f5a9795426,
  .reference_value_size = 2,
  .degree = 1,
  .block_size = 2,
  .family = "Lagrange",

  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_30501addce65c40f51d2333fb2adc3f5a9795426
};

// End of code for element element_30501addce65c40f51d2333fb2adc3f5a9795426

// Code for dofmap dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87



void tabulate_entity_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 1;
        dofs[1] = 2;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        break;
    case 2:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87[4] = { 1, 2, 3, 0 };

ufc_dofmap dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87 =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', triangle, 1)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 1,
  .num_entity_dofs = num_entity_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87

// Code for dofmap dofmap_30501addce65c40f51d2333fb2adc3f5a9795426

ufc_dofmap* sub_dofmaps_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426[2] = { &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87, &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87 };

void tabulate_entity_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
}
}

void tabulate_entity_closure_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 1;
        dofs[1] = 2;
        break;
    case 1:
        dofs[0] = 0;
        dofs[1] = 2;
        break;
    case 2:
        dofs[0] = 0;
        dofs[1] = 1;
        break;
    }
    break;
case 2:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 1;
        dofs[2] = 2;
        break;
    }
    break;
}
}

int num_entity_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426[4] = { 1, 0, 0, 0 };

int num_entity_closure_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426[4] = { 1, 2, 3, 0 };

ufc_dofmap dofmap_30501addce65c40f51d2333fb2adc3f5a9795426 =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)",
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .block_size = 2,
  .num_entity_dofs = num_entity_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426,
  .num_entity_closure_dofs = num_entity_closure_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426,
  .tabulate_entity_closure_dofs = tabulate_entity_closure_dofs_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_30501addce65c40f51d2333fb2adc3f5a9795426
};

// End of code for dofmap dofmap_30501addce65c40f51d2333fb2adc3f5a9795426

// Code for integral integral_1d33afccde6662b8b39cd6f6cf291d04ebb6b306

void tabulate_tensor_integral_1d33afccde6662b8b39cd6f6cf291d04ebb6b306(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_083[1] = { 0.5 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE3_C0_D01_Q083[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
    static const double FE4_C0_D10_Q083[1][1][1][3] = { { { { -1.0, 1.0, 0.0 } } } };
    // Quadrature loop independent computations for quadrature rule 083
    const double J_c0 = coordinate_dofs[0] * FE4_C0_D10_Q083[0][0][0][0] + coordinate_dofs[3] * FE4_C0_D10_Q083[0][0][0][1] + coordinate_dofs[6] * FE4_C0_D10_Q083[0][0][0][2];
    const double J_c3 = coordinate_dofs[1] * FE3_C0_D01_Q083[0][0][0][0] + coordinate_dofs[4] * FE3_C0_D01_Q083[0][0][0][1] + coordinate_dofs[7] * FE3_C0_D01_Q083[0][0][0][2];
    const double J_c1 = coordinate_dofs[0] * FE3_C0_D01_Q083[0][0][0][0] + coordinate_dofs[3] * FE3_C0_D01_Q083[0][0][0][1] + coordinate_dofs[6] * FE3_C0_D01_Q083[0][0][0][2];
    const double J_c2 = coordinate_dofs[1] * FE4_C0_D10_Q083[0][0][0][0] + coordinate_dofs[4] * FE4_C0_D10_Q083[0][0][0][1] + coordinate_dofs[7] * FE4_C0_D10_Q083[0][0][0][2];
    ufc_scalar_t sp_083[20];
    sp_083[0] = J_c0 * J_c3;
    sp_083[1] = J_c1 * J_c2;
    sp_083[2] = sp_083[0] + -1 * sp_083[1];
    sp_083[3] = J_c0 / sp_083[2];
    sp_083[4] = (-1 * J_c1) / sp_083[2];
    sp_083[5] = sp_083[3] * sp_083[3];
    sp_083[6] = sp_083[3] * sp_083[4];
    sp_083[7] = sp_083[4] * sp_083[4];
    sp_083[8] = J_c3 / sp_083[2];
    sp_083[9] = (-1 * J_c2) / sp_083[2];
    sp_083[10] = sp_083[9] * sp_083[9];
    sp_083[11] = sp_083[8] * sp_083[9];
    sp_083[12] = sp_083[8] * sp_083[8];
    sp_083[13] = sp_083[5] + sp_083[10];
    sp_083[14] = sp_083[6] + sp_083[11];
    sp_083[15] = sp_083[12] + sp_083[7];
    sp_083[16] = fabs(sp_083[2]);
    sp_083[17] = sp_083[13] * sp_083[16];
    sp_083[18] = sp_083[14] * sp_083[16];
    sp_083[19] = sp_083[15] * sp_083[16];
    for (int iq = 0; iq < 1; ++iq)
    {
        const ufc_scalar_t fw0 = sp_083[19] * weights_083[iq];
        const ufc_scalar_t fw1 = sp_083[18] * weights_083[iq];
        const ufc_scalar_t fw2 = sp_083[17] * weights_083[iq];
        ufc_scalar_t t0[3];
        ufc_scalar_t t1[3];
        for (int i = 0; i < 3; ++i)
        {
            t0[i] = fw0 * FE4_C0_D10_Q083[0][0][0][i] + fw1 * FE3_C0_D01_Q083[0][0][0][i];
            t1[i] = fw1 * FE4_C0_D10_Q083[0][0][0][i] + fw2 * FE3_C0_D01_Q083[0][0][0][i];
        }
        for (int i = 0; i < 3; ++i)
        {
            for (int j = 0; j < 3; ++j)
            {
                ufc_scalar_t acc0 = 0;
                acc0 += FE4_C0_D10_Q083[0][0][0][j] * t0[i];
                acc0 += FE3_C0_D01_Q083[0][0][0][j] * t1[i];
                A[3 * i + j] += acc0;
            }
        }
    }
}



ufc_integral integral_1d33afccde6662b8b39cd6f6cf291d04ebb6b306 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor = tabulate_tensor_integral_1d33afccde6662b8b39cd6f6cf291d04ebb6b306,
};

// End of code for integral integral_1d33afccde6662b8b39cd6f6cf291d04ebb6b306

// Code for integral integral_eb8004c26e818f76c60141234b6d9437aea7585c

void tabulate_tensor_integral_eb8004c26e818f76c60141234b6d9437aea7585c(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation)
{
    // Quadrature rules
    static const double weights_48e[3] = { 0.1666666666666667, 0.1666666666666667, 0.1666666666666667 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE3_C0_Q48e[1][1][3][3] =
        { { { { 0.6666666666666667, 0.1666666666666666, 0.1666666666666667 },
              { 0.1666666666666667, 0.1666666666666666, 0.6666666666666666 },
              { 0.1666666666666668, 0.6666666666666666, 0.1666666666666667 } } } };
    static const double FE4_C0_D10_Q48e[1][1][1][3] = { { { { -1.0, 1.0, 0.0 } } } };
    static const double FE4_C1_D01_Q48e[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule 48e
    const double J_c0 = coordinate_dofs[0] * FE4_C0_D10_Q48e[0][0][0][0] + coordinate_dofs[3] * FE4_C0_D10_Q48e[0][0][0][1] + coordinate_dofs[6] * FE4_C0_D10_Q48e[0][0][0][2];
    const double J_c3 = coordinate_dofs[1] * FE4_C1_D01_Q48e[0][0][0][0] + coordinate_dofs[4] * FE4_C1_D01_Q48e[0][0][0][1] + coordinate_dofs[7] * FE4_C1_D01_Q48e[0][0][0][2];
    const double J_c1 = coordinate_dofs[0] * FE4_C1_D01_Q48e[0][0][0][0] + coordinate_dofs[3] * FE4_C1_D01_Q48e[0][0][0][1] + coordinate_dofs[6] * FE4_C1_D01_Q48e[0][0][0][2];
    const double J_c2 = coordinate_dofs[1] * FE4_C0_D10_Q48e[0][0][0][0] + coordinate_dofs[4] * FE4_C0_D10_Q48e[0][0][0][1] + coordinate_dofs[7] * FE4_C0_D10_Q48e[0][0][0][2];
    ufc_scalar_t sp_48e[4];
    sp_48e[0] = J_c0 * J_c3;
    sp_48e[1] = J_c1 * J_c2;
    sp_48e[2] = sp_48e[0] + -1 * sp_48e[1];
    sp_48e[3] = fabs(sp_48e[2]);
    for (int iq = 0; iq < 3; ++iq)
    {
        // Quadrature loop body setup for quadrature rule 48e
        // Varying computations for quadrature rule 48e
        ufc_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 3; ++ic)
            w0 += w[ic] * FE3_C0_Q48e[0][0][iq][ic];
        ufc_scalar_t sv_48e[1];
        sv_48e[0] = sp_48e[3] * w0;
        const ufc_scalar_t fw0 = sv_48e[0] * weights_48e[iq];
        for (int i = 0; i < 3; ++i)
            A[i] += fw0 * FE3_C0_Q48e[0][0][iq][i];
    }
}

bool enabled_coefficients_integral_eb8004c26e818f76c60141234b6d9437aea7585c[1] = { false };

ufc_integral integral_eb8004c26e818f76c60141234b6d9437aea7585c =
{
  .enabled_coefficients = enabled_coefficients_integral_eb8004c26e818f76c60141234b6d9437aea7585c,
  .tabulate_tensor = tabulate_tensor_integral_eb8004c26e818f76c60141234b6d9437aea7585c,
};

// End of code for integral integral_eb8004c26e818f76c60141234b6d9437aea7585c

// Code for form form_4a5635c2e319573a99e1a891162527b8ece1d4d8


ufc_dofmap* dofmaps_form_4a5635c2e319573a99e1a891162527b8ece1d4d8[2] = { &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87, &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87 };
ufc_finite_element* finite_elements_form_4a5635c2e319573a99e1a891162527b8ece1d4d8[2] = { &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87, &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87 };

// Return a list of the coefficient names.
const char** coefficient_name_form_4a5635c2e319573a99e1a891162527b8ece1d4d8(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_4a5635c2e319573a99e1a891162527b8ece1d4d8(void)
{
return NULL;
}

int* integral_ids_form_4a5635c2e319573a99e1a891162527b8ece1d4d8(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_4a5635c2e319573a99e1a891162527b8ece1d4d8[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_4a5635c2e319573a99e1a891162527b8ece1d4d8;
default:
    return NULL;
}
}

int num_integrals_form_4a5635c2e319573a99e1a891162527b8ece1d4d8(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_4a5635c2e319573a99e1a891162527b8ece1d4d8(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_4a5635c2e319573a99e1a891162527b8ece1d4d8[1] = { &integral_1d33afccde6662b8b39cd6f6cf291d04ebb6b306 };
switch (integral_type)
{
case cell:
    return integrals_cell_form_4a5635c2e319573a99e1a891162527b8ece1d4d8;
default:
    return NULL;
}
}

ufc_form form_4a5635c2e319573a99e1a891162527b8ece1d4d8 =
{

  .signature = "ce26b0e24fae604fc9c102aa2255fc8942822ef3358564be2e04340dc6d2a14e43a32892995077cd83f53e0d7b026df7e460cd9f1f5a0ee6b6e11406db961a8a",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_4a5635c2e319573a99e1a891162527b8ece1d4d8,
  .constant_name_map = constant_name_form_4a5635c2e319573a99e1a891162527b8ece1d4d8,

  .finite_elements = finite_elements_form_4a5635c2e319573a99e1a891162527b8ece1d4d8,
  .dofmaps = dofmaps_form_4a5635c2e319573a99e1a891162527b8ece1d4d8,

  .integral_ids = integral_ids_form_4a5635c2e319573a99e1a891162527b8ece1d4d8,
  .num_integrals = num_integrals_form_4a5635c2e319573a99e1a891162527b8ece1d4d8,

  .integrals = integrals_form_4a5635c2e319573a99e1a891162527b8ece1d4d8
};

// Alias name
ufc_form* form_poisson_a = &form_4a5635c2e319573a99e1a891162527b8ece1d4d8;

ufc_function_space* functionspace_form_poisson_a(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.dofmap = &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u =
{
.finite_element = &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.dofmap = &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
return NULL;

}

// End of code for form form_4a5635c2e319573a99e1a891162527b8ece1d4d8

// Code for form form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52

int original_coefficient_position_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52[1] = { 0 };
ufc_dofmap* dofmaps_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52[2] = { &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87, &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87 };
ufc_finite_element* finite_elements_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52[2] = { &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87, &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87 };

// Return a list of the coefficient names.
const char** coefficient_name_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52(void)
{
static const char* names[1] = { "f" };
return names;
}

// Return a list of the constant names.
const char** constant_name_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52(void)
{
return NULL;
}

int* integral_ids_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52;
default:
    return NULL;
}
}

int num_integrals_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52[1] = { &integral_eb8004c26e818f76c60141234b6d9437aea7585c };
switch (integral_type)
{
case cell:
    return integrals_cell_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52;
default:
    return NULL;
}
}

ufc_form form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52 =
{

  .signature = "59735b6e5199cd9ab7dfed9d38c6b178340fb81e6a6fe206cf194b4982897df58ed817115db15ced297d2bc0f178c1358d4d8ab663a1cba93a39dc83522bf2c4",
  .rank = 1,
  .num_coefficients = 1,
  .num_constants = 0,
  .original_coefficient_position = original_coefficient_position_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,

  .coefficient_name_map = coefficient_name_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,
  .constant_name_map = constant_name_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,

  .finite_elements = finite_elements_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,
  .dofmaps = dofmaps_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,

  .integral_ids = integral_ids_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,
  .num_integrals = num_integrals_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52,

  .integrals = integrals_form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52
};

// Alias name
ufc_form* form_poisson_L = &form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52;

ufc_function_space* functionspace_form_poisson_L(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.dofmap = &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_f =
{
.finite_element = &element_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.dofmap = &dofmap_00d4fefb25fc8ed8563136725dd7f20b01dabe87,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "f") == 0)
    return &functionspace_f;
return NULL;

}

// End of code for form form_0d1e67a283fa63ae74908f991f7d0bdd56b6cb52
